# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

# container: mcr.microsoft.com/playwright:v1.24.0-focal

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.15.1'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install (with build included)'

- script: |
    npx playwright install-deps chromium
  displayName: 'Install playwright deps'

- script: |
    npm run check-for-uncommitted-files
  displayName: 'Check if there are no uncommitted files'

- script: |
    npm run lint
  displayName: 'Lint and prettier check'

- script: |
    npm run build-storybook
  displayName: 'Build static storybook'

- script: |
    npm run test:ci
  displayName: 'Run unit and e2e tests'

- script: |
    git config --global user.email "$GITHUB_EMAIL" && git config --global user.name "$GITHUB_USER" && bash ./scripts/branch-deployment.sh
  displayName: 'Gh-Pages - Push Featurebranch'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    GITHUB_EMAIL: $(GITHUB_EMAIL)
    GITHUB_USER: $(GITHUB_USER)
    PR_SOURCE_BRANCH_NAME: $(System.PullRequest.SourceBranch)
    SOURCE_BRANCH_NAME: $(Build.SourceBranchName)

- bash: |
    ./scripts/branch-deployment-notifier.sh
  displayName: 'Gh-Pages - Notify Users about successful deployment'
  env:
    SLACK_TOKEN: $(SLACK_TOKEN)
    PR_SOURCE_BRANCH_NAME: $(System.PullRequest.SourceBranch)
    SOURCE_BRANCH_NAME: $(Build.SourceBranchName)

- task: CopyFiles@2
  displayName: 'Stage Artifacts'
  inputs:
    SourceFolder: ./storybook-static
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'
